platform :ios, '11.4'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'git@github.com:W2-Global-Data/cocoapods-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

pre_install do |installer|
	installer.analysis_result.specifications.each do |s|
        if s.name == 'Alamofire'
            s.swift_version = '5.0'
        end
    end
end


target 'reactnative' do
  use_frameworks!
  use_native_modules!
  # Pods for reactnative
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'w2-document-verification-capture-client-react-native', :path => '../node_modules/@w2-global-data/w2-document-verification-capture-client-react-native'

  pod 'w2-document-verification-client-react-native', :path => '../node_modules/@w2-global-data/w2-document-verification-client-react-native'

  pod 'w2-facial-comparison-capture-client-react-native', :path => '../node_modules/@w2-global-data/w2-facial-comparison-capture-client-react-native'

  pod 'w2-facial-comparison-client-react-native', :path => '../node_modules/@w2-global-data/w2-facial-comparison-client-react-native'

  target 'reactnativeTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'reactnative-tvOS' do
  # Pods for reactnative-tvOS

  target 'reactnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['AcuantiOSSDKV11', 'KeychainAccess', 'Socket.IO-Client-Swift', 'Starscream', 'SwiftyJSON'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
      target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
